### ISSUE TITLE
Release 2.0 version for Caliburn Micro 2.0

### ISSUE THREAD

**Issue by kamranayub** [kamranayub/CaliburnBindableAppBar#23]
- [x] Fix Panorama sample

**Comment by matopeto** [comment]
Yes, nuget 2.0 package would be great.

**Comment by altso** [comment]
@kamranayub do you plan to release a nuget package for v2.0?

**Comment by kamranayub** [comment]
Yes, I should have some time this weekend but I can't promise. I think the
issue with the panorama/pivot is resolved just have to sit down and test it.

**Comment by kamranayub** [comment]
Done. Thanks @theothernt for fixing the Panorama sample!

**Comment by altso** [comment]
Nice work. Thank you.
